# Do not use make's built-in implicit rules or built-in variables. Throw
# a warning if an undefined variable is referenced.
MAKEFLAGS	+= -rR --warn-undefined-variables

# Delete any output files generated by a failed rule.
.DELETE_ON_ERROR:

SHELL		:= bash
.SHELLFLAGS	:= -eu -o pipefail -c

CC		:= gcc
CFLAGS		:= -std=c17 -pipe
RELEASE_CFLAGS	:= -O2 -march=native -flto=auto -DNDEBUG
DEBUG_CFLAGS	:= -Og -g3 -DDEBUG -fsanitize=address,leak,undefined -Werror

WARN_CFLAGS	:= -Wall -Wextra -pedantic -pedantic-errors -Wformat=2	\
		   -Wshadow -Wstrict-prototypes -Wstrict-overflow=2	\
		   -Wvla -Wredundant-decls -Wnested-externs -Wcast-qual	\
		   -Wfloat-equal -Wdouble-promotion -Wpointer-arith	\
		   -Wundef -Winit-self -Wwrite-strings -Wlogical-op	\
		   -Wconversion -Walloc-zero

CLANGD_CFLAGS	:= $(CFLAGS) $(RELEASE_CFLAGS) $(WARN_CFLAGS)		\
		   -Wreserved-identifier -Wno-unused-function		\
		   -Wno-empty-translation-unit

CLANGD_FILE	:= compile_flags.txt

LDFLAGS		:= -Wl,-O1,--sort-common,--as-needed
LDLIBS		:=
INCLUDES	:=

SRC_DIR		:= ./src
OBJ_DIR		:= ./obj
SOURCES		:= $(wildcard $(SRC_DIR)/*.c)
OBJECTS		:= $(SOURCES:$(SRC_DIR)/%.c=$(OBJ_DIR)/%.o)

TARGET		:= cobalt

.PHONY: all clean debug release

all: release

debug: CFLAGS := $(CFLAGS) $(DEBUG_CFLAGS) $(WARN_CFLAGS)
debug: $(TARGET)

release: CFLAGS := $(CFLAGS) $(RELEASE_CFLAGS) $(WARN_CFLAGS)
release: $(TARGET)

clean:
	@rm -rf $(OBJ_DIR)
	@rm -f $(TARGET) $(CLANGD_FILE) gmon.out .clangd ~*

$(TARGET): $(CLANGD_FILE)
$(TARGET): $(OBJECTS)
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) $(INCLUDES) $(OBJECTS) -o $@

$(OBJECTS): $(OBJ_DIR)
$(OBJECTS): $(OBJ_DIR)/%.o : $(SRC_DIR)/%.c
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@

$(OBJ_DIR):
	@mkdir -p $@

$(CLANGD_FILE):
	@echo "$(CLANGD_CFLAGS)" | xargs -n 1 > $@
